extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=exif
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sodium
extension=sqlite3
extension=xsl
extension=zip
extension=pcntl
extension=bcmath
zend_extension=opcache

; Laravel overrides
upload_max_filesize=64M
post_max_size=64M
memory_limit=512M
max_execution_time=120
date.timezone=Asia/Qatar